In [1]:
import numpy as np

In [5]:
a=np.random.randint(30,99,20)
a

array([44, 40, 98, 75, 72, 53, 87, 96, 62, 85, 65, 97, 73, 90, 63, 40, 95,
       90, 79, 71])

In [7]:
a[-1]

71

In [9]:
a[9]

85

In [11]:
a=np.random.randint(30,99,(8,9))
a

array([[39, 71, 89, 49, 69, 94, 64, 96, 97],
       [75, 64, 37, 55, 39, 42, 70, 96, 66],
       [39, 87, 51, 53, 71, 98, 79, 92, 73],
       [94, 85, 55, 46, 77, 33, 82, 38, 65],
       [76, 81, 34, 97, 65, 62, 45, 57, 40],
       [73, 72, 43, 83, 93, 51, 53, 56, 54],
       [64, 72, 76, 36, 30, 83, 97, 39, 41],
       [36, 78, 74, 69, 72, 87, 55, 95, 56]])

In [13]:
a[1:5]

array([[75, 64, 37, 55, 39, 42, 70, 96, 66],
       [39, 87, 51, 53, 71, 98, 79, 92, 73],
       [94, 85, 55, 46, 77, 33, 82, 38, 65],
       [76, 81, 34, 97, 65, 62, 45, 57, 40]])

In [15]:
a[7,0]

36

In [ ]:
import pandas as 